"""pbcft_schema

Revision ID: 7112be250f87
Revises: 8d23259525ad
Create Date: 2026-04-14 02:05:55.376451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7112be250f87'
down_revision: Union[str, None] = '8d23259525ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pbcft', sa.Column('nome', sa.String(length=256), nullable=False))
    op.add_column('pbcft', sa.Column('investimento', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('pbcft', sa.Column('fundos', sa.JSON(), nullable=False))
    op.add_column('pbcft', sa.Column('perfil_risco', sa.String(length=10), nullable=False))
    op.add_column('pbcft', sa.Column('is_pep', sa.Boolean(), nullable=False))
    op.add_column('pbcft', sa.Column('doc_identificacao', sa.Boolean(), nullable=False))
    op.add_column('pbcft', sa.Column('doc_morada', sa.Boolean(), nullable=False))
    op.add_column('pbcft', sa.Column('doc_rendimentos', sa.Boolean(), nullable=False))
    op.add_column('pbcft', sa.Column('data_entrada_compliance', sa.Date(), nullable=True))
    op.add_column('pbcft', sa.Column('data_decisao', sa.Date(), nullable=True))
    op.add_column('pbcft', sa.Column('tipo_decisao', sa.String(length=32), nullable=True))
    op.add_column('pbcft', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_pbcft_id'), 'pbcft', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pbcft_id'), table_name='pbcft')
    op.drop_column('pbcft', 'created_at')
    op.drop_column('pbcft', 'tipo_decisao')
    op.drop_column('pbcft', 'data_decisao')
    op.drop_column('pbcft', 'data_entrada_compliance')
    op.drop_column('pbcft', 'doc_rendimentos')
    op.drop_column('pbcft', 'doc_morada')
    op.drop_column('pbcft', 'doc_identificacao')
    op.drop_column('pbcft', 'is_pep')
    op.drop_column('pbcft', 'perfil_risco')
    op.drop_column('pbcft', 'fundos')
    op.drop_column('pbcft', 'investimento')
    op.drop_column('pbcft', 'nome')
    # ### end Alembic commands ###
